import { Drop, CategoryConfig, DropCategory, GhostMark, QuestTrail, NFTBadge } from "@/types";
import { BADGE_ICONS } from "@/utils/badgeIcons";

export var CATEGORY_CONFIG: Record<DropCategory, CategoryConfig> = {
  lore: { icon: "👻", color: "#a78bfa", label: "Lore" },
  quest: { icon: "🔮", color: "#60a5fa", label: "Quest" },
  secret: { icon: "⚰️", color: "#f472b6", label: "Secret" },
  ritual: { icon: "🕯️", color: "#fbbf24", label: "Ritual" },
  treasure: { icon: "💀", color: "#34d399", label: "Treasure" },
};

export var MOCK_DROPS: Drop[] = [
  {
    id: "drop-1",
    location: { lat: 52.2297, lng: 21.0122 },
    message: "First soul lost in the Old Town... the cobblestones remember.",
    isClaimed: false,
    finderReward: 0.05,
    category: "lore",
    createdBy: "phantom.sol",
    createdAt: "2026-02-12",
    audiusTrackId: "777353110", // Example track ID
  },
  {
    id: "drop-2",
    location: { lat: 52.2319, lng: 21.0067 },
    message: "A forgotten oracle speaks beneath the Palace of Culture. Listen closely...",
    isClaimed: false,
    finderReward: 0.12,
    category: "quest",
    createdBy: "spectre.sol",
    createdAt: "2026-02-13",
  },
  {
    id: "drop-3",
    location: { lat: 52.235, lng: 21.0 },
    message: "The coffin builder's secret recipe for digital immortality — now on-chain.",
    isClaimed: true,
    finderReward: 0.08,
    category: "secret",
    createdBy: "wraith.sol",
    createdAt: "2026-02-11",
    claimedBy: "finder.sol",
    claimedAt: "2026-02-12",
  },
  {
    id: "drop-4",
    location: { lat: 52.227, lng: 21.018 },
    message: "Light a candle at the Vistula crossroads at midnight. The blockchain never forgets.",
    isClaimed: false,
    finderReward: 0.15,
    category: "ritual",
    createdBy: "shade.sol",
    createdAt: "2026-02-14",
  },
  {
    id: "drop-5",
    location: { lat: 52.24, lng: 20.995 },
    message: "The necromancer's apprentice left coordinates here. Final destination: Łazienki.",
    isClaimed: false,
    finderReward: 0.25,
    category: "treasure",
    createdBy: "lich.sol",
    createdAt: "2026-02-12",
  },
  {
    id: "drop-6",
    location: { lat: 52.233, lng: 21.025 },
    message: "Moonlit whispers echo through the Praga district...",
    isClaimed: false,
    finderReward: 0.03,
    category: "lore",
    createdBy: "banshee.sol",
    createdAt: "2026-02-13",
  },
  {
    id: "drop-7",
    location: { lat: 52.22, lng: 21.01 },
    message: "The key to the on-chain crypt is hidden in plain sight near Mokotów.",
    isClaimed: false,
    finderReward: 0.2,
    category: "quest",
    createdBy: "revenant.sol",
    createdAt: "2026-02-14",
  },
  // ─── New drops for density ──────────────────────────────────────────────
  {
    id: "drop-8",
    location: { lat: 52.2255, lng: 21.0305 },
    message: "Under Poniatowski Bridge, a dead protocol left its last message...",
    isClaimed: false,
    finderReward: 0.07,
    category: "secret",
    createdBy: "cipher.sol",
    createdAt: "2026-02-14",
  },
  {
    id: "drop-9",
    location: { lat: 52.2395, lng: 21.0453 },
    message: "The Zoo district holds more than animals. PDA seeds: zoo_vault_001",
    isClaimed: false,
    finderReward: 0.1,
    category: "treasure",
    createdBy: "keeper.sol",
    createdAt: "2026-02-13",
  },
  {
    id: "drop-10",
    location: { lat: 52.2188, lng: 21.0215 },
    message: "Burn rate: 13,250 CU. Cheaper than a candle. Light it.",
    isClaimed: false,
    finderReward: 0.04,
    category: "ritual",
    createdBy: "pinocchio.sol",
    createdAt: "2026-02-15",
  },
  {
    id: "drop-11",
    location: { lat: 52.248, lng: 21.015 },
    message: "Żoliborz remembers. The old resistance used dead drops too.",
    isClaimed: false,
    finderReward: 0.06,
    category: "lore",
    createdBy: "historia.sol",
    createdAt: "2026-02-14",
  },
  {
    id: "drop-12",
    location: { lat: 52.2155, lng: 20.985 },
    message: "Solana graveyard shift: when CU is cheapest, secrets are loudest.",
    isClaimed: true,
    finderReward: 0.09,
    category: "secret",
    createdBy: "nightshift.sol",
    createdAt: "2026-02-12",
    claimedBy: "dawn.sol",
    claimedAt: "2026-02-13",
  },
  {
    id: "drop-13",
    location: { lat: 52.237, lng: 21.035 },
    message: "Three wallets converge here. The ritual requires all three signatures.",
    isClaimed: false,
    finderReward: 0.3,
    category: "ritual",
    createdBy: "trinity.sol",
    createdAt: "2026-02-15",
  },
  {
    id: "drop-14",
    location: { lat: 52.222, lng: 21.005 },
    message: "The last anchor dev switched to Pinocchio here. Zero deps, zero regrets.",
    isClaimed: false,
    finderReward: 0.18,
    category: "quest",
    createdBy: "nativedev.sol",
    createdAt: "2026-02-15",
  },
  // ─── Global Drops ────────────────────────────────────────────────────────
  {
    id: "drop-global-1",
    location: { lat: 40.7580, lng: -73.9855 },
    message: "Times Square Ghosts: The digital billboards hide the truth about the 2024 crash.",
    isClaimed: false,
    finderReward: 0.5,
    category: "lore",
    createdBy: "nyc_spectre.sol",
    createdAt: "2026-02-16",
    audiusTrackId: "2013859664",
  },
  {
    id: "drop-global-2",
    location: { lat: 51.5055, lng: -0.0754 },
    message: "Tower Bridge Secret: Beneath the Thames, a cold wallet awaits its master.",
    isClaimed: false,
    finderReward: 0.8,
    category: "secret",
    createdBy: "london_wraith.sol",
    createdAt: "2026-02-17",
  },
  {
    id: "drop-global-3",
    location: { lat: 35.6618, lng: 139.7022 },
    message: "Shibuya Crossing Ritual: Synchronize your wallets at the stroke of midnight.",
    isClaimed: false,
    finderReward: 1.2,
    category: "ritual",
    createdBy: "tokyo_lich.sol",
    createdAt: "2026-02-18",
    audiusTrackId: "123456789",
  },
  {
    id: "drop-global-4",
    location: { lat: -22.9519, lng: -43.2105 },
    message: "Corcovado Treasure: The view is divine, but the bounty is real.",
    isClaimed: false,
    finderReward: 2.0,
    category: "treasure",
    createdBy: "rio_king.sol",
    createdAt: "2026-02-19",
  },
  {
    id: "drop-global-5",
    location: { lat: -33.8568, lng: 151.2153 },
    message: "Sydney Opera Echo: Listen to the phantom's aria near the harbor.",
    isClaimed: false,
    finderReward: 0.3,
    category: "lore",
    createdBy: "sydney_banshee.sol",
    createdAt: "2026-02-20",
    audiusTrackId: "987654321",
  },
  {
    id: "drop-global-6",
    location: { lat: 48.8584, lng: 2.2945 },
    message: "Eiffel Tower Quest: Climb the digital heights of Solana.",
    isClaimed: false,
    finderReward: 0.1,
    category: "quest",
    createdBy: "paris_ghost.sol",
    createdAt: "2026-02-21",
  },
  // ─── North America ───────────────────────────────────────────────────────
  {
    id: "drop-na-1",
    location: { lat: 37.7749, lng: -122.4194 },
    message: "San Francisco Lore: Where the first Web3 nodes began to hum.",
    isClaimed: false,
    finderReward: 0.4,
    category: "lore",
    createdBy: "sf_pioneer.sol",
    createdAt: "2026-02-15",
  },
  {
    id: "drop-na-2",
    location: { lat: 25.7617, lng: -80.1918 },
    message: "Miami South Beach Bounty: Proof of Vibe is the only consensus that matters.",
    isClaimed: false,
    finderReward: 1.5,
    category: "treasure",
    createdBy: "miami_vice.sol",
    createdAt: "2026-02-16",
    audiusTrackId: "2013859664",
  },
  {
    id: "drop-na-3",
    location: { lat: 30.2672, lng: -97.7431 },
    message: "Austin Secret: Deep in the heart of Texas, a private key is buried.",
    isClaimed: false,
    finderReward: 0.2,
    category: "secret",
    createdBy: "austin_weird.sol",
    createdAt: "2026-02-17",
  },
  {
    id: "drop-na-4",
    location: { lat: 43.6532, lng: -79.3832 },
    message: "Toronto CN Tower: Scanning the horizon for the next bull run.",
    isClaimed: false,
    finderReward: 0.6,
    category: "quest",
    createdBy: "canuck_dev.sol",
    createdAt: "2026-02-18",
  },
  {
    id: "drop-na-5",
    location: { lat: 19.4326, lng: -99.1332 },
    message: "Mexico City Ritual: The ancient spirits demand a burn of 1000 BONK.",
    isClaimed: false,
    finderReward: 0.9,
    category: "ritual",
    createdBy: "aztec_coder.sol",
    createdAt: "2026-02-19",
  },
  // ─── South America ───────────────────────────────────────────────────────
  {
    id: "drop-sa-1",
    location: { lat: -34.6037, lng: -58.3816 },
    message: "Buenos Aires Obelisco: Deflation is a myth, but this reward is real.",
    isClaimed: false,
    finderReward: 0.3,
    category: "lore",
    createdBy: "tango_dev.sol",
    createdAt: "2026-02-14",
  },
  {
    id: "drop-sa-2",
    location: { lat: 6.2442, lng: -75.5812 },
    message: "Medellin Secret: The mountain air carries whispers of a lost seed phrase.",
    isClaimed: false,
    finderReward: 0.7,
    category: "secret",
    createdBy: "paisa_ghost.sol",
    createdAt: "2026-02-15",
  },
  // ─── Europe (Expanded) ───────────────────────────────────────────────────
  {
    id: "drop-eu-1",
    location: { lat: 52.5200, lng: 13.4050 },
    message: "Berlin Brandenburg Gate: Tearing down the walls between chains.",
    isClaimed: false,
    finderReward: 0.5,
    category: "lore",
    createdBy: "berlin_techno.sol",
    createdAt: "2026-02-13",
  },
  {
    id: "drop-eu-2",
    location: { lat: 52.3676, lng: 4.9041 },
    message: "Amsterdam Secret: Floating on the canals of decentralization.",
    isClaimed: false,
    finderReward: 0.4,
    category: "secret",
    createdBy: "tulip_mania.sol",
    createdAt: "2026-02-12",
  },
  {
    id: "drop-eu-3",
    location: { lat: 38.7223, lng: -9.1393 },
    message: "Lisbon Belem Tower: Setting sail for the new frontiers of Solana.",
    isClaimed: false,
    finderReward: 0.3,
    category: "lore",
    createdBy: "fado_explorer.sol",
    createdAt: "2026-02-14",
    audiusTrackId: "2013859664",
  },
  {
    id: "drop-eu-4",
    location: { lat: 41.8902, lng: 12.4922 },
    message: "Rome Colosseum Ritual: Glads of the governance arena, unite!",
    isClaimed: false,
    finderReward: 1.2,
    category: "ritual",
    createdBy: "caesar_dao.sol",
    createdAt: "2026-02-15",
  },
  {
    id: "drop-eu-5",
    location: { lat: 50.0755, lng: 14.4378 },
    message: "Prague Charles Bridge: Gothic architecture meets digital persistence.",
    isClaimed: false,
    finderReward: 0.4,
    category: "lore",
    createdBy: "golem_maker.sol",
    createdAt: "2026-02-16",
  },
  // ─── Asia (Expanded) ─────────────────────────────────────────────────────
  {
    id: "drop-as-1",
    location: { lat: 37.5665, lng: 126.9780 },
    message: "Seoul Secret: Neon lights and ultra-fast finality.",
    isClaimed: false,
    finderReward: 0.8,
    category: "secret",
    createdBy: "kpop_staker.sol",
    createdAt: "2026-02-17",
  },
  {
    id: "drop-as-2",
    location: { lat: 1.3521, lng: 103.8198 },
    message: "Singapore Marina Bay Treasure: The future of finance is a garden in the sky.",
    isClaimed: false,
    finderReward: 2.5,
    category: "treasure",
    createdBy: "merlion_whale.sol",
    createdAt: "2026-02-18",
    audiusTrackId: "2013859664",
  },
  {
    id: "drop-as-3",
    location: { lat: 13.7563, lng: 100.5018 },
    message: "Bangkok Ritual: Incense, temples, and on-chain immutability.",
    isClaimed: false,
    finderReward: 1.0,
    category: "ritual",
    createdBy: "thai_ghost.sol",
    createdAt: "2026-02-19",
  },
  {
    id: "drop-as-4",
    location: { lat: 25.2048, lng: 55.2708 },
    message: "Dubai Burj Khalifa Treasure: Scaling the heights of the blockchain.",
    isClaimed: false,
    finderReward: 3.0,
    category: "treasure",
    createdBy: "desert_king.sol",
    createdAt: "2026-02-20",
  },
  {
    id: "drop-as-5",
    location: { lat: 18.9220, lng: 72.8347 },
    message: "Mumbai Gateway Lore: The digital revolution will not be centralized.",
    isClaimed: false,
    finderReward: 0.2,
    category: "lore",
    createdBy: "masala_dev.sol",
    createdAt: "2026-02-21",
  },
  // ─── Africa ──────────────────────────────────────────────────────────────
  {
    id: "drop-af-1",
    location: { lat: -33.9249, lng: 18.4241 },
    message: "Cape Town Lore: At the edge of the world, we build.",
    isClaimed: false,
    finderReward: 0.4,
    category: "lore",
    createdBy: "safari_node.sol",
    createdAt: "2026-02-22",
  },
  {
    id: "drop-af-2",
    location: { lat: 6.4549, lng: 3.3887 },
    message: "Lagos Secret: The pulse of a new digital economy.",
    isClaimed: false,
    finderReward: 0.6,
    category: "secret",
    createdBy: "naija_ninja.sol",
    createdAt: "2026-02-23",
  },
  {
    id: "drop-af-3",
    location: { lat: 29.9792, lng: 31.1342 },
    message: "Cairo Pyramids Ritual: Ancient secrets for modern validators.",
    isClaimed: false,
    finderReward: 5.0,
    category: "ritual",
    createdBy: "pharaoh_dev.sol",
    createdAt: "2026-02-24",
  },
  // ─── Oceania ─────────────────────────────────────────────────────────────
  {
    id: "drop-oc-1",
    location: { lat: -36.8485, lng: 174.7633 },
    message: "Auckland Secret: First to see the new block.",
    isClaimed: false,
    finderReward: 0.3,
    category: "secret",
    createdBy: "kiwi_hacker.sol",
    createdAt: "2026-02-25",
  },
];

export var WARSAW_CENTER = { lat: 52.2297, lng: 21.0122 };
export var DEFAULT_ZOOM = 13;

// ─── Ghost Mark Emojis ───────────────────────────────────────────────────────

export var GHOST_EMOJIS = [
  { emoji: "👻" as const, label: "Ghost" },
  { emoji: "💭" as const, label: "Thought" },
  { emoji: "⚠️" as const, label: "Warning" },
  { emoji: "📸" as const, label: "Photo spot" },
  { emoji: "🎵" as const, label: "Music" },
  { emoji: "💀" as const, label: "Danger" },
  { emoji: "🔥" as const, label: "Hot spot" },
  { emoji: "❄️" as const, label: "Chill" },
];

// ─── Mock Ghost Marks ────────────────────────────────────────────────────────

export var MOCK_GHOSTS: GhostMark[] = [
  { id: "g1", location: { lat: 52.2310, lng: 21.0060 }, message: "Best pierogi spot in Warsaw, trust me 🥟", emoji: "🔥", createdBy: "anon", createdAt: Date.now() - 3600000, reactions: 7 },
  { id: "g2", location: { lat: 52.2280, lng: 21.0150 }, message: "Watch out, slippery stairs near the metro", emoji: "⚠️", createdBy: "anon", createdAt: Date.now() - 7200000, reactions: 3 },
  { id: "g3", location: { lat: 52.2340, lng: 21.0020 }, message: "Amazing sunset view from this rooftop", emoji: "📸", createdBy: "anon", createdAt: Date.now() - 1800000, reactions: 12 },
  { id: "g4", location: { lat: 52.2250, lng: 21.0250 }, message: "Street musician plays here every evening", emoji: "🎵", createdBy: "anon", createdAt: Date.now() - 5400000, reactions: 5 },
  { id: "g5", location: { lat: 52.2370, lng: 21.0100 }, message: "This alley gives major spooky vibes at night", emoji: "💀", createdBy: "anon", createdAt: Date.now() - 14400000, reactions: 8 },
  // Global Ghosts
  { id: "g-na-1", location: { lat: 37.7882, lng: -122.4075 }, message: "Union Square vibes! 🌉", emoji: "💭", createdBy: "sf_native", createdAt: Date.now() - 3600000, reactions: 15 },
  { id: "g-eu-1", location: { lat: 51.5074, lng: -0.1278 }, message: "Mind the gap! 🚇", emoji: "⚠️", createdBy: "londoner", createdAt: Date.now() - 7200000, reactions: 9 },
  { id: "g-as-1", location: { lat: 35.6895, lng: 139.6917 }, message: "Shinjuku neon is peaking! 🏮", emoji: "📸", createdBy: "tokyo_ghoul", createdAt: Date.now() - 1800000, reactions: 24 },
  { id: "g-sa-1", location: { lat: -23.5505, lng: -46.6333 }, message: "São Paulo heat! 🔥", emoji: "🔥", createdBy: "paulista", createdAt: Date.now() - 5400000, reactions: 12 },
  { id: "g-oc-1", location: { lat: -33.8688, lng: 151.2093 }, message: "Chilling at Darling Harbour ⛵", emoji: "❄️", createdBy: "aussie_dev", createdAt: Date.now() - 14400000, reactions: 7 },
];

// ─── Quest Trails ────────────────────────────────────────────────────────────

export var MOCK_TRAILS: QuestTrail[] = [
  {
    id: "trail-1",
    name: "Old Town Haunting",
    description: "Follow the ghosts through Warsaw's medieval heart. Visit 4 haunted spots and claim the final treasure.",
    icon: "🏰",
    color: "#a78bfa",
    reward: 0.5,
    createdBy: "lich.sol",
    difficulty: "easy",
    estimatedTime: "30 min",
    distance: "1.2 km",
    waypoints: [
      { id: "t1-w1", location: { lat: 52.2497, lng: 21.0122 }, name: "Castle Square", hint: "Where the old king's ghost still wanders", order: 1 },
      { id: "t1-w2", location: { lat: 52.2510, lng: 21.0080 }, name: "Cathedral Crypt", hint: "Listen for whispers in the stone walls", order: 2 },
      { id: "t1-w3", location: { lat: 52.2490, lng: 21.0040 }, name: "Barbican Gate", hint: "The ancient defenders left something behind", order: 3 },
      { id: "t1-w4", location: { lat: 52.2475, lng: 21.0005 }, name: "Freta Street End", hint: "Marie Curie's spirit guards the final drop", order: 4 },
    ],
  },
  {
    id: "trail-2",
    name: "Vistula Death March",
    description: "A riverside quest along the Vistula. Each checkpoint reveals a piece of Solana's buried history.",
    icon: "🌊",
    color: "#60a5fa",
    reward: 0.8,
    createdBy: "revenant.sol",
    difficulty: "medium",
    estimatedTime: "45 min",
    distance: "2.8 km",
    waypoints: [
      { id: "t2-w1", location: { lat: 52.2350, lng: 21.0350 }, name: "Copernicus Centre", hint: "The stars align for those who seek", order: 1 },
      { id: "t2-w2", location: { lat: 52.2300, lng: 21.0300 }, name: "Świętokrzyski Bridge", hint: "Cross the bridge between worlds", order: 2 },
      { id: "t2-w3", location: { lat: 52.2250, lng: 21.0280 }, name: "National Stadium", hint: "Where champions fall and rise again", order: 3 },
      { id: "t2-w4", location: { lat: 52.2200, lng: 21.0320 }, name: "Saska Kępa", hint: "The quiet district hides the loudest secret", order: 4 },
      { id: "t2-w5", location: { lat: 52.2180, lng: 21.0380 }, name: "Riverside End", hint: "The Vistula reveals its final truth", order: 5 },
    ],
  },
  {
    id: "trail-3",
    name: "Crypto Graveyard Tour",
    description: "Visit the burial sites of dead crypto projects around Śródmieście. Learn from the fallen.",
    icon: "⚰️",
    color: "#f472b6",
    reward: 1.0,
    createdBy: "phantom.sol",
    difficulty: "hard",
    estimatedTime: "60 min",
    distance: "3.5 km",
    waypoints: [
      { id: "t3-w1", location: { lat: 52.2319, lng: 21.0067 }, name: "Palace of Culture", hint: "Where centralized dreams went to die", order: 1 },
      { id: "t3-w2", location: { lat: 52.2270, lng: 21.0180 }, name: "Nowy Świat", hint: "The new world wasn't ready for web3", order: 2 },
      { id: "t3-w3", location: { lat: 52.2220, lng: 21.0150 }, name: "Łazienki Gate", hint: "Even kings couldn't hold their bags", order: 3 },
      { id: "t3-w4", location: { lat: 52.2150, lng: 21.0200 }, name: "Mokotów Fields", hint: "Yield farming's final resting place", order: 4 },
      { id: "t3-w5", location: { lat: 52.2100, lng: 21.0100 }, name: "Southern Crypt", hint: "The last validator signed off here", order: 5 },
      { id: "t3-w6", location: { lat: 52.2050, lng: 21.0050 }, name: "Wilanów Gate", hint: "From this graveyard, Solana rises", order: 6 },
    ],
  },
  {
    id: "trail-sunrise",
    name: "Tutorial: Sunrise Onboarding",
    description: "New to Solana? This trail will guide you through creating a wallet, using Tapestry, and discovering on-chain social. Highly recommended for new explorers!",
    icon: "☀️",
    color: "#f59e0b",
    reward: 0.3,
    createdBy: "sunrise_dao",
    difficulty: "easy",
    estimatedTime: "20 min",
    distance: "0.8 km",
    waypoints: [
      { id: "ts-w1", location: { lat: 52.2290, lng: 21.0110 }, name: "Genesis Point", hint: "Start your journey. Every great protocol began with a single block.", order: 1 },
      { id: "ts-w2", location: { lat: 52.2305, lng: 21.0150 }, name: "Social Node", hint: "Follow another explorer on Tapestry to proceed.", order: 2 },
      { id: "ts-w3", location: { lat: 52.2320, lng: 21.0180 }, name: "Graveyard Gate", hint: "Learn why building in a bear market is the best time.", order: 3 },
    ],
  },
];

// ─── NFT Badge Definitions ───────────────────────────────────────────────────

export var BADGE_DEFINITIONS: NFTBadge[] = [
  { id: "first-blood",      name: "First Blood",      description: "Claim your first drop",               icon: BADGE_ICONS["first-blood"],      threshold: 1,   thresholdType: "claims",     rarity: "common",    color: "#ef4444" },
  { id: "explorer",         name: "Explorer",         description: "Claim 5 drops",                       icon: BADGE_ICONS["explorer"],         threshold: 5,   thresholdType: "claims",     rarity: "rare",      color: "#3b82f6" },
  { id: "phantom-hunter",   name: "Phantom Hunter",   description: "Claim 10 drops",                      icon: BADGE_ICONS["phantom-hunter"],   threshold: 10,  thresholdType: "claims",     rarity: "epic",      color: "#a78bfa" },
  { id: "lich-lord",        name: "Lich Lord",        description: "Claim 25 drops",                      icon: BADGE_ICONS["lich-lord"],        threshold: 25,  thresholdType: "claims",     rarity: "legendary", color: "#fbbf24" },
  { id: "gravedigger",      name: "Gravedigger",      description: "Create 3 drops",                      icon: BADGE_ICONS["gravedigger"],      threshold: 3,   thresholdType: "creates",    rarity: "common",    color: "#9ca3af" },
  { id: "haunter",          name: "Haunter",          description: "Leave 5 ghost marks",                 icon: BADGE_ICONS["haunter"],          threshold: 5,   thresholdType: "ghosts",     rarity: "rare",      color: "#8b5cf6" },
  { id: "trail-walker",     name: "Trail Walker",     description: "Complete a quest trail",              icon: BADGE_ICONS["trail-walker"],     threshold: 1,   thresholdType: "trails",     rarity: "rare",      color: "#10b981" },
  { id: "social-butterfly", name: "Social Butterfly", description: "Follow 5 explorers on Tapestry",      icon: BADGE_ICONS["social-butterfly"], threshold: 5,   thresholdType: "reputation", rarity: "rare",      color: "#ec4899" },
  { id: "torque-loyalist",  name: "Torque Loyalist",  description: "Maintain a 7-day streak (Torque)",    icon: BADGE_ICONS["torque-loyalist"],  threshold: 7,   thresholdType: "claims",     rarity: "epic",      color: "#f59e0b" },
  { id: "magicblock-hero",  name: "Magic Hero",       description: "Master of gaming quests",             icon: BADGE_ICONS["magicblock-hero"],  threshold: 50,  thresholdType: "reputation", rarity: "legendary", color: "#3b82f6" },
  { id: "legend",           name: "Legend",           description: "Reach 200 reputation",                icon: BADGE_ICONS["legend"],           threshold: 200, thresholdType: "reputation", rarity: "legendary", color: "#f59e0b" },
];
